server:
  port: 8080
api:
  prefix: /api/v1
spring:
  application:
    name: Tour-app
  datasource:
    url: jdbc:mariadb://localhost:3306/tour_app?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secretKey: 90c85b588e8d468d45cf5a70a5517dc6507a0655d7ea0664f6eb70dd4d76394e
  valid-duration: 86400
  refresh-duration: 86400






